# Derived from config_min.yaml, augmented for causal instruction optimization.
# Keeps original values unless changed for optimization mode.

data:
  task_name: harmful
  split: test_public
  train_fraction: 0.5
  shuffle_seed: 0
  behavior_ids: []
  sample_ids:
  detailed_behaviors: 
  hint_included: 
  n_irrelevant_tools: 0

# lm_name: Main model for generation and mutation
models:
  lm_name: openai/gpt-4o-mini
  lm_temperature: 0
  seed: 42
  max_tokens: 4096
  refusal_judge_model: openai/gpt-4o
  semantic_judge_model: openai/gpt-4o
  api_base: https://api.shubiaobiao.cn/v1/

# (Unrelated original optimization block retained; not used by causal optimization loop but need to be kept for config parsing)
optimization:
  optim_seed: 6793115
  auto_mode: light
  num_threads: 4
  algorithm: mipro
  run_optimization: false
  optimize_refusal: false

experiment:
  name: agentharm
  uri: http://127.0.0.1:5000

causal:
  enabled: true
  # Either set run_name OR model_lm_name (kept from minimal config)
  run_name: 
  param_key: "WebReActAgent.react.predict.signature.instructions"
  child_prefix: "eval_full_"
  # Increase prompt budget for broader seed set for optimization
  max_collected_prompts: 3
  seed: 42
  output_dir: "results/causal_optimization"
  # --- Optimization mode switches ---
  optimization:
    frontier_size: 10
    max_generations: 5           # Slightly higher than default 10
    random_seed: 42
    target_completion: 1.0
    target_refusal: 1.0
    max_candidates_evaluated:  # Cap total evaluations (frontier + mutations)
    max_data_size:       # Dataset size (for debugging)
    minibatch_size: 4
    segment_lm_name: openai/gpt-4o-mini # model to use for segmentation
    segment_model_api_base: https://api.shubiaobiao.cn/v1/
