# Derived from config_min.yaml, augmented for causal instruction optimization.
# Keeps original values unless changed for optimization mode.

data:
  task_name: harmful
  split: test_public
  train_fraction: 0.4
  shuffle_seed: 0
  behavior_ids: []
  sample_ids: "1-1,1-2,1-3,1-4,10-1,10-2,10-3,10-4"
  detailed_behaviors: 
  hint_included: 
  n_irrelevant_tools: 0

models:
  lm_name: openai/gemini-2.5-flash
  lm_temperature: 0
  seed: 42
  max_tokens: 4096
  refusal_judge_model: openai/gpt-4o-mini
  semantic_judge_model: openai/gpt-4o-mini
  api_base: https://run.v36.cm/v1/
  # headers:
  #   x-foo: "true"

# (Unrelated original optimization block retained; not used by causal optimization loop but need to be kept for config parsing)
optimization:
  optim_seed: 6793115
  auto_mode: light
  num_threads: 4
  algorithm: mipro
  run_optimization: false

experiment:
  name: agentharm
  uri: http://127.0.0.1:5000

causal:
  enabled: true
  # Either set run_name OR model_lm_name (kept from minimal config)
  run_name: 
  model_lm_name: openai/gpt-4o-mini
  run_is_optim: true
  param_key: "WebReActAgent.react.predict.signature.instructions"
  child_prefix: "eval_full_"
  # Increase prompt budget for broader seed set for optimization
  max_prompts: 10
  # Intervention types are ignored in pure optimization mode, but kept for parity
  intervention_types: ["drop_instruction", "shuffle_order", "mask_step", "replace_tool_hint"]
  seed: 42
  output_dir: "results/causal_optimization"
  # --- Optimization mode switches ---
  optimization:
    population_size: 4           # Larger than default 16 for more diversity
    max_generations: 2           # Slightly higher than default 10
    random_seed: 42
    target_completion: 1.0
    target_refusal: 1.0
    max_candidates_evaluated: 10 # Cap total evaluations (frontier + mutations)
    max_eval_samples: 5      # Evaluate on fewer samples for speed
    segmentation_model: openai/gpt-4o-mini # Which model to use for segmentation & mutations
    openai_api_base: https://run.v36.cm/v1/
